name: Bug Report
description: Create a report to help us resolve a defect or rendering issue
title: "bug: [Short description of issue]"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to report an issue in the Davarus Bell Platform codebase!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '/buy.html'
        2. Click on 'GET MY HOME & LOAN MATCH NOW'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true
